<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>se.fk.data</groupId>
        <artifactId>ffa</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ffa-demo</artifactId>
    <dependencies>
        <dependency><groupId>se.fk.data</groupId><artifactId>ffa-persistence</artifactId><version>${project.version}</version></dependency>
        <dependency>
            <groupId>se.fk.data</groupId>
            <artifactId>ffa-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>se.fk.data</groupId>
            <artifactId>hundbidrag</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>demo</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.6.3</version>
                        <executions>
                            <execution>
                                <id>demo</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>java</executable>
                                    <workingDirectory>${maven.multiModuleProjectDirectory}</workingDirectory>
                                    <arguments>
                                        <argument>--module-path</argument>
                                        <modulepath/>
                                        <argument>--module</argument>
                                        <argument>se.fk.ffa.demo/se.fk.demo.Demo</argument>
                                        <argument>${maven.multiModuleProjectDirectory}/target/demo-yrkande.json</argument>
                                        <argument>${ffa.demo.action}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
